WhaleSpotting/Controllers/SightingController.cs
using System.Diagnostics;
using System.Dynamic;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WhaleSpotting.Data;
using WhaleSpotting.Models;
using WhaleSpotting.ViewModels;

namespace WhaleSpotting.Controllers;

[Route("sighting")]
[Authorize]
public class SightingController : Controller
{
    private readonly ILogger<SightingController> _logger;
    private readonly ApplicationDbContext _context;
    private readonly UserManager<IdentityUser> _userManager;

    public SightingController
    (
        ILogger<SightingController> logger,
        ApplicationDbContext context,
        UserManager<IdentityUser> userManager
    ) {
        _logger = logger;
        _context = context;
        _userManager = userManager;
    }

    [AllowAnonymous]
    public IActionResult Index()
    {
        if (User.Identity!.IsAuthenticated)
        {
            var wsUser = _context.WsUsers!
                .Single(u => u.IdentityUser!.Id == _userManager.GetUserId(User));
            ViewData["WsUserId"] = wsUser.Id;
        }

        var approvedSightings = _context.Sightings!
            .Where(sighting => sighting.Approved)
            .Include(s => s.User)
            .Include(p => p.Photos)
            .Include(s => s.Species)
            .ToList();

        return View(approvedSightings);
    }
    
    [HttpPost("")]
    public IActionResult NewSighting([FromForm] NewSightingFormViewModel newSightingViewModel)
    {
        var wsUser = _context.WsUsers!
            .Single(u => u.IdentityUser!.Id == _userManager.GetUserId(User));
        ViewData["WsUserId"] = wsUser.Id;
        
        try
        {
            var newSighting = new Sighting();
            newSighting.Latitude = newSightingViewModel.Sighting!.Latitude;
            newSighting.Longitude = newSightingViewModel.Sighting!.Longitude;
            newSighting.Description = newSightingViewModel.Sighting!.Description;
            newSighting.Species = newSightingViewModel.Sighting!.Species;
            newSighting.Date = DateOnly.FromDateTime(newSightingViewModel.Sighting!.Date);
            newSighting.Photos = new List<Photo> { new Photo { Image = newSightingViewModel.Sighting!.PhotoUrl } };

            var speciesId = newSightingViewModel.SpeciesId;
            Species selectedSpecies = _context.Species!
                .Where(speciesCheck => speciesCheck.Id == speciesId)
                .First();
            newSighting.Species = selectedSpecies;

            newSighting.User = wsUser; 

            _context.Sightings?.Add(newSighting);
            _context.SaveChanges();
            
            return RedirectToAction("SightingSubmitted");
    }
    catch (Exception ex)
    {
        _logger.LogError(ex, "An error occurred while adding the sighting.");

        TempData["ErrorMessage"] = "An error occurred while adding the sighting.";
    }

    var species = _context.Species!.ToList();
    var viewModel = new NewSightingFormViewModel
    {
        ListOfSpecies = species,
        Sighting = new SightingViewModel(),
    };

    ViewData["ConfirmationMessage"] = TempData["ConfirmationMessage"];
    ViewData["ErrorMessage"] = TempData["ErrorMessage"];

    return View("NewSightingForm", viewModel);
}

    [HttpGet("new")]
    public IActionResult NewSightingForm()
    {
        var wsUser = _context.WsUsers!
            .Single(u => u.IdentityUser!.Id == _userManager.GetUserId(User));
        ViewData["WsUserId"] = wsUser.Id;
        
        var species = _context.Species!.ToList();
        var sighting = new SightingViewModel();
        var viewModel = new NewSightingFormViewModel
        {
            ListOfSpecies = species,
            Sighting = sighting,
        };
        return View(viewModel);
    }

    [HttpGet("submitted")]
    public IActionResult SightingSubmitted()
    {
        return View();
    }
}

WhaleSpotting/Controllers/SpeciesController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using WhaleSpotting.Data;
using WhaleSpotting.Models;

namespace WhaleSpotting.Controllers;

[Route("species")]
public class SpeciesController : Controller
{
    private readonly ILogger<SpeciesController> _logger;
    private readonly ApplicationDbContext _context;
    private readonly UserManager<IdentityUser> _userManager;

    public SpeciesController
    (
        ILogger<SpeciesController> logger, 
        ApplicationDbContext context, 
        UserManager<IdentityUser> userManager
    ) {
        _logger = logger;
        _context = context;
        _userManager = userManager;
    }

    [HttpGet("{id}")]
    public IActionResult UniqueSpecies([FromRoute] int id)
    {
        if (User.Identity!.IsAuthenticated)
        {
            var wsUser = _context.WsUsers!
                .Single(u => u.IdentityUser!.Id == _userManager.GetUserId(User));
            ViewData["WsUserId"] = wsUser.Id;
        }

        var species = _context.Species;
        var uniqueSpecies= species!.Single(s => s.Id == id);

        return View(uniqueSpecies);
    }

    public IActionResult Index()
    {
         if (User.Identity!.IsAuthenticated)
        {
            var wsUser = _context.WsUsers!
                .Single(u => u.IdentityUser!.Id == _userManager.GetUserId(User));
            ViewData["WsUserId"] = wsUser.Id;
        }

        var species = _context.Species!.ToList();
        return View(species);
    }
}

WhaleSpotting/Controllers/UserController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WhaleSpotting.Data;
using WhaleSpotting.Models;

namespace WhaleSpotting.Controllers;

[Route("users")]
public class UserController : Controller
{
    private readonly ILogger<UserController> _logger;
    private readonly ApplicationDbContext _context;
    private readonly UserManager<IdentityUser> _userManager;
    public UserController
    (
        ILogger<UserController> logger,
        ApplicationDbContext context,
        UserManager<IdentityUser> userManager
    ) {
        _logger = logger;
        _context = context;
        _userManager = userManager;
    }

    [HttpGet("{id}")]
    public IActionResult UserPage([FromRoute] int id)
    {
        if (User.Identity!.IsAuthenticated)
        {
            var wsUser = _context.WsUsers!
                .Single(u => u.IdentityUser!.Id == _userManager.GetUserId(User));
            ViewData["WsUserId"] = wsUser.Id;
        }

        var user = _context.WsUsers!
            .Include(u => u.Sightings)
            .Single(u => u.Id == id);

        return View(user);  
    }

    [HttpGet("{id}/edit")]
    public IActionResult EditUserForm(int id)
    {
        if (User.Identity!.IsAuthenticated)
        {
            var wsUser = _context.WsUsers!
                .Single(u => u.IdentityUser!.Id == _userManager.GetUserId(User));
            ViewData["WsUserId"] = wsUser.Id;
        }

        var user = _context.WsUsers!.Find(id);
        return View(user);
    }

    [HttpPost("{id}")]
    public IActionResult EditUser
    (
        [FromRoute] int id,
        [FromForm] WsUser modifiedUser
    ) {
        if (User.Identity!.IsAuthenticated)
        {
            var wsUser = _context.WsUsers!
                .Single(u => u.IdentityUser!.Id == _userManager.GetUserId(User));
            ViewData["WsUserId"] = wsUser.Id;
        }

        var user = _context.WsUsers!
            .Single(u => u.Id == id);

        if (!string.IsNullOrEmpty(modifiedUser.Name))
        {
            user.Name = modifiedUser.Name;
        }

        if (!string.IsNullOrEmpty(modifiedUser.ProfileImageUrl))
        {
           user.ProfileImageUrl = modifiedUser.ProfileImageUrl; 
        }

        if (!string.IsNullOrEmpty(modifiedUser.Bio))
        {
            user.Bio = modifiedUser.Bio;
        }

        _context.SaveChanges();

        return RedirectToAction("UserPage", new RouteValueDictionary { { "id", id } });
    }
}

WhaleSpotting/Views/Shared/_Layout.cshtml
@{
    bool isLoggedIn = ViewData["WsUserId"] != null;
    int loggedInWsUserId = isLoggedIn ? (int)ViewData["WsUserId"]! : 0;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - WhaleSpotting</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/WhaleSpotting.styles.css" asp-append-version="true"/>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"
        integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY="
        crossorigin=""/>
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Syne"/>    
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Whale Spotting</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Species" asp-action="Index">Whales</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Sighting" asp-action="Index">Sightings</a>
                    </li>
                    @if (isLoggedIn)
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="UserPage" asp-route-id="@loggedInWsUserId">Profile</a>
                        </li>
                    }
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="GetInvolved">Get involved</a>
                    </li>    
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                </ul>
                <partial name="_LoginPartial"/>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main">
        @RenderBody()
         <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"
            integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo="
            crossorigin=""></script>
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2023 - WhaleSpotting - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WhaleSpotting/Views/Shared/_MyListPartial.cshtml
@model List<Sighting> 
    
<!-- Add Bootstrap and jQuery CDNs to your HTML for the carousel to work -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

@{
    List<string> speciesInAllSightings = new();
}

<form method="get" action="Sighting">
    <select name="specie" id="specie">
        <option value="filter" disabled>filter</option>
        <option value="All" selected>All</option>

        @foreach (var sighting in Model)
        {
            if (sighting.Species != null && !speciesInAllSightings.Contains(sighting.Species.Slug!))
            {
                <option value="@sighting.Species.Slug">@sighting.Species.Name</option>
                speciesInAllSightings.Add(sighting.Species.Slug!);
            }
        }
    </select>
    <input type="submit" value="Submit">
</form>

@{
    string FilterBy = Context.Request.Query["specie"];
    if (FilterBy == "All" || FilterBy == null)
    {
        foreach (var sighting in Model)
        {
            speciesInAllSightings.Add(sighting.Species!.Slug!);
        }
    }
    else
    {
        speciesInAllSightings.Clear();
        speciesInAllSightings.Add(FilterBy!);
    }
}

<div class="sightings-list row row-cols-1 row-cols-md-4 g-4">
    @foreach (var sighting in Model)
    {
        if (speciesInAllSightings.Contains(sighting.Species!.Slug!))
        {
            <ul style="list-style: none; padding: 0;">
                <div class="card mb-3 rounded-9" style="width: 18rem; float:left; margin:10px;">

                    <div id="carousel_@(sighting.Id)" class="carousel slide" data-ride="carousel">
                        <div class="carousel-inner">

                            @if (sighting.Photos != null)
                            {
                                foreach (var photo in sighting.Photos)
                                {
                                    <div class="carousel-item @(photo == sighting.Photos.First() ? "active" : "")">
                                        <img  class="card-img-top" width="318" height="318" src="@photo.Image" alt="A picture of a whale sighting">
                                    </div>
                                }      
                            }
                            <a class="carousel-control-prev" href="#carousel_@(sighting.Id)" role="button" data-slide="prev">
                                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                <span class="sr-only"></span>
                            </a>
                            <a class="carousel-control-next" href="#carousel_@(sighting.Id)" role="button" data-slide="next">
                                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                <span class="sr-only"></span>
                            </a>
                        </div>        
                        <div class="card-body" style="height: 250px; overflow:auto;">
                            <p class="card-text">Latitude: @sighting.Latitude</p>
                            <p class="card-text">Longitude: @sighting.Longitude</p>
                            <p class="card-text">Date: @sighting.Date</p>
                            <p class="card-text">Description: @sighting.Description</p>
                        </div>
                    </div>
                </div>
            </ul>
        }
    }
</div>

WhaleSpotting/Views/Shared/_MyMapPartial.cshtml
@model List<WhaleSpotting.Sighting>

<div id="map" style="height: 800px;"></div>